begin;

create or replace function private.druid_remove_source_types(p_mechanics jsonb,p_source_key text,p_types text[])
returns jsonb language sql immutable set search_path='' as $$
select coalesce(jsonb_agg(m order by ord) filter(where not(coalesce(m->>'sourceKey','')=p_source_key and (m->>'type')=any(p_types))),'[]'::jsonb)
from jsonb_array_elements(coalesce(p_mechanics,'[]'::jsonb)) with ordinality x(m,ord);
$$;

create or replace function private.normalize_druid_modern_circles(p_campaign_id uuid)
returns void language plpgsql security definer set search_path='' as $$
declare v_id uuid;
begin
  -- LAND
  select id into v_id from public.rule_templates where campaign_id=p_campaign_id and is_active and catalog_key='subclass:druid:land' order by version desc limit 1;
  if v_id is not null then
    update public.rule_template_levels l set mechanics=private.druid_patch_feature(l.mechanics,'lands-aid',
      'Магическим действием потрать 1 использование Дикой формы и выбери точку в пределах 60 футов. В сфере радиусом 10 футов выбранные существа делают спасбросок Телосложения против Сл твоих заклинаний: при провале получают 2к6 некротического урона, при успехе — половину. Одно выбранное существо в сфере восстанавливает 2к6 HP. На 10 уровне обе величины становятся 3к6, на 14 — 4к6.',
      jsonb_build_object('version',1,'kind','area_damage_and_healing','activation','magic_action','cost',jsonb_build_object('resource','wild_shape','amount',1),'rangeFeet',60,'radiusFeet',10,'save',jsonb_build_object('ability','constitution','dc','spell','success','half'),'damage',jsonb_build_object('type','necrotic','dice','2d6'),'healing',jsonb_build_object('dice','2d6','targets',1),'scaling',jsonb_build_object('10','3d6','14','4d6')))
    where l.template_id=v_id and l.level=3;

    update public.rule_template_levels l set mechanics=l.mechanics||jsonb_build_array(
      jsonb_build_object('id','lands-aid-action-l10','type','action','sourceKey','lands-aid','key','lands_aid','grantOperation','REPLACE','priority',10,'label','Помощь земли','economy','action','range',jsonb_build_object('kind','ranged','normal',60,'unit','ft'),'damage',jsonb_build_array(jsonb_build_object('key','necrotic','damageType','necrotic','count',3,'sides',6)),'resourceKey','wild_shape','resourceCost',1,'tags',jsonb_build_array('class','save','healing')),
      jsonb_build_object('id','lands-aid-rules-l10','type','grant','target','feature','sourceKey','lands-aid','key','subclass:druid:land:lands-aid','grantOperation','REPLACE','priority',10,'payload',jsonb_build_object('label','Помощь земли','description','Урон и лечение Помощи земли увеличиваются до 3к6. Остальные условия способности не меняются.','mechanic',jsonb_build_object('version',1,'kind','area_damage_and_healing','activation','magic_action','cost',jsonb_build_object('resource','wild_shape','amount',1),'rangeFeet',60,'radiusFeet',10,'save',jsonb_build_object('ability','constitution','dc','spell','success','half'),'damage',jsonb_build_object('type','necrotic','dice','3d6'),'healing',jsonb_build_object('dice','3d6','targets',1))))
    ) where l.template_id=v_id and l.level=10 and not exists(select 1 from jsonb_array_elements(l.mechanics)m where m->>'id'='lands-aid-action-l10');

    update public.rule_template_levels l set mechanics=l.mechanics||jsonb_build_array(
      jsonb_build_object('id','lands-aid-action-l14','type','action','sourceKey','lands-aid','key','lands_aid','grantOperation','REPLACE','priority',14,'label','Помощь земли','economy','action','range',jsonb_build_object('kind','ranged','normal',60,'unit','ft'),'damage',jsonb_build_array(jsonb_build_object('key','necrotic','damageType','necrotic','count',4,'sides',6)),'resourceKey','wild_shape','resourceCost',1,'tags',jsonb_build_array('class','save','healing')),
      jsonb_build_object('id','lands-aid-rules-l14','type','grant','target','feature','sourceKey','lands-aid','key','subclass:druid:land:lands-aid','grantOperation','REPLACE','priority',14,'payload',jsonb_build_object('label','Помощь земли','description','Урон и лечение Помощи земли увеличиваются до 4к6. Остальные условия способности не меняются.','mechanic',jsonb_build_object('version',1,'kind','area_damage_and_healing','activation','magic_action','cost',jsonb_build_object('resource','wild_shape','amount',1),'rangeFeet',60,'radiusFeet',10,'save',jsonb_build_object('ability','constitution','dc','spell','success','half'),'damage',jsonb_build_object('type','necrotic','dice','4d6'),'healing',jsonb_build_object('dice','4d6','targets',1))))
    ) where l.template_id=v_id and l.level=14 and not exists(select 1 from jsonb_array_elements(l.mechanics)m where m->>'id'='lands-aid-action-l14');

    update public.rule_template_levels l set mechanics=private.druid_remove_source_types(l.mechanics,'natural-recovery',array['resource','action'])||jsonb_build_array(
      jsonb_build_object('id','land-natural-recovery-free-cast-resource','type','resource','sourceKey','natural-recovery','key','land_natural_recovery_free_cast','label','Бесплатное круговое заклинание','max',1,'recharge','long_rest','initial','full'),
      jsonb_build_object('id','land-natural-recovery-free-cast-action','type','action','sourceKey','natural-recovery','key','land_natural_recovery_free_cast','label','Природное восстановление · заклинание','economy','magic_action','resourceKey','land_natural_recovery_free_cast','resourceCost',1,'tags',jsonb_build_array('class','spell','alternate_payment')),
      jsonb_build_object('id','land-natural-recovery-slots-resource','type','resource','sourceKey','natural-recovery','key','land_natural_recovery_slots','label','Восстановление ячеек','max',1,'recharge','long_rest','initial','full'),
      jsonb_build_object('id','land-natural-recovery-slots-action','type','action','sourceKey','natural-recovery','key','land_natural_recovery_slots','label','Природное восстановление · ячейки','economy','short_rest','resourceKey','land_natural_recovery_slots','resourceCost',1,'tags',jsonb_build_array('class','resource_conversion'))
    ) where l.template_id=v_id and l.level=6;
    update public.rule_template_levels l set mechanics=private.druid_patch_feature(l.mechanics,'natural-recovery',
      'У способности две независимые части. Раз за долгий отдых одно подготовленное круговое заклинание 1+ уровня творится без траты ячейки. Отдельно, после короткого отдыха раз за долгий отдых можно вернуть потраченные ячейки с суммой уровней не выше половины уровня друида, округляя вверх; ячейки 6+ уровня вернуть нельзя.',
      jsonb_build_object('version',1,'kind','dual_recovery','freeCircleSpell',jsonb_build_object('uses',1,'recharge','long_rest','minimumSpellLevel',1),'shortRestSlots',jsonb_build_object('uses',1,'recharge','long_rest','budget','ceil(source.level/2)','maximumSlotLevel',5)))
    where l.template_id=v_id and l.level=6;
    update public.rule_template_levels l set mechanics=l.mechanics||jsonb_build_array(jsonb_build_object('id','land-sanctuary-move','type','action','sourceKey','natures-sanctuary','key','natures_sanctuary_move','label','Святилище природы · передвинуть','economy','bonus_action','range',jsonb_build_object('kind','ranged','normal',120,'unit','ft'),'tags',jsonb_build_array('class','requires_active:natures_sanctuary'))) where l.template_id=v_id and l.level=14 and not exists(select 1 from jsonb_array_elements(l.mechanics)m where m->>'id'='land-sanctuary-move');
  end if;

  -- MOON
  select id into v_id from public.rule_templates where campaign_id=p_campaign_id and is_active and catalog_key='subclass:druid:moon' order by version desc limit 1;
  if v_id is not null then
    update public.rule_template_levels l set mechanics=private.druid_patch_feature(l.mechanics,'circle-forms','Максимальный CR зверя равен уровню друида / 3. В зверином облике КД равен 13 + модификатор Мудрости, если это выше КД самого зверя. Запас HP берётся из блока характеристик зверя.',jsonb_build_object('version',1,'kind','wild_shape_upgrade','dependsOn',jsonb_build_array('wild_shape'),'maxBeastCR','floor(source.level/3)','minimumArmorClass',jsonb_build_object('base',13,'ability','wisdom'),'formHitPoints','beast_stat_block')) where l.template_id=v_id and l.level=3;
    update public.rule_template_levels l set mechanics=private.druid_patch_feature(l.mechanics,'improved-circle-forms','Пока друид находится в Дикой форме, при каждом попадании атакой зверя можно оставить обычный тип урона атаки или заменить его на излучающий. К спасброскам Телосложения в форме добавляется модификатор Мудрости.',jsonb_build_object('version',1,'kind','wild_shape_upgrade','dependsOn',jsonb_build_array('wild_shape_active'),'attackDamageChoice',jsonb_build_array('normal','radiant'),'constitutionSaveBonus',jsonb_build_object('reference','abilities.wisdom.modifier'))) where l.template_id=v_id and l.level=6;
    update public.rule_template_levels l set mechanics=(select coalesce(jsonb_agg(case when m->>'id'='moon-step-action-l14' then jsonb_set(m,'{sourceKey}',to_jsonb('lunar-form'::text),true) else m end order by ord) filter(where m->>'id'<>'moon-step-upgrade-rules'),'[]'::jsonb) from jsonb_array_elements(l.mechanics) with ordinality x(m,ord)) where l.template_id=v_id and l.level=14;
    update public.rule_template_levels l set mechanics=private.druid_patch_feature(l.mechanics,'lunar-form','Один раз на каждом своём ходу попадание атакой звериной формы наносит дополнительно 2к10 излучающего урона. Лунный шаг также переносит одного согласного союзника в пределах 10 футов от друида; после телепорта союзник появляется в пределах 10 футов от точки назначения.',jsonb_build_object('version',1,'kind','wild_shape_and_action_upgrade','dependsOn',jsonb_build_array('wild_shape_active'),'extraDamage',jsonb_build_object('frequency','once_per_turn','dice','2d10','type','radiant'),'upgradesAction','moonlight_step','passenger',jsonb_build_object('willing',true,'originRangeFeet',10,'destinationRangeFeet',10))) where l.template_id=v_id and l.level=14;
  end if;

  -- SEA
  select id into v_id from public.rule_templates where campaign_id=p_campaign_id and is_active and catalog_key='subclass:druid:sea' order by version desc limit 1;
  if v_id is not null then
    update public.rule_template_levels l set mechanics=private.druid_patch_feature(l.mechanics,'wrath-of-the-sea','Бонусным действием потрать 1 использование Дикой формы: на 10 минут вокруг тебя возникает 5-футовая эманация. При активации и затем бонусным действием выбери цель в эманации. Она делает спасбросок Телосложения против Сл заклинаний; при провале получает к6 холодного урона числом, равным модификатору Мудрости, минимум 1, а Большую или меньшую цель можно оттолкнуть на расстояние до 15 футов. Эманация не требует концентрации и заканчивается при повторной активации, добровольном прекращении или недееспособности.',jsonb_build_object('version',1,'kind','persistent_emanation','stateKey','wrath_of_the_sea_active','activation','bonus_action','cost',jsonb_build_object('resource','wild_shape','amount',1),'durationMinutes',10,'emanationFeet',5,'save',jsonb_build_object('ability','constitution','dc','spell'),'damage',jsonb_build_object('type','cold','diceCount',jsonb_build_object('reference','abilities.wisdom.modifier','minimum',1),'sides',6),'failedSave',jsonb_build_object('pushUpToFeet',15,'maximumSize','large'),'endsOn',jsonb_build_array('dismiss','reactivate','incapacitated'))) where l.template_id=v_id and l.level=3;
    update public.rule_template_levels l set mechanics=l.mechanics||jsonb_build_array(jsonb_build_object('id','sea-wrath-surge-l6','type','action','sourceKey','aquatic-affinity','key','wrath_of_the_sea_surge','grantOperation','REPLACE','priority',6,'label','Гнев моря','economy','bonus_action','range',jsonb_build_object('kind','melee','reach',10,'unit','ft'),'tags',jsonb_build_array('class','save','requires_active:wrath_of_the_sea'))) where l.template_id=v_id and l.level=6 and not exists(select 1 from jsonb_array_elements(l.mechanics)m where m->>'id'='sea-wrath-surge-l6');
    update public.rule_template_levels l set mechanics=private.druid_patch_feature(l.mechanics,'aquatic-affinity','Эманация Гнева моря увеличивается с 5 до 10 футов. Кроме того, скорость плавания друида равна его обычной Скорости.',jsonb_build_object('version',1,'kind','feature_upgrade','upgrades','wrath_of_the_sea','emanationFeet',10,'swimSpeed',jsonb_build_object('equals','combat.speed'))) where l.template_id=v_id and l.level=6;
    update public.rule_template_levels l set mechanics=private.druid_patch_feature(l.mechanics,'stormborn','Пока активен Гнев моря, друид получает скорость полёта, равную обычной Скорости, и сопротивление холоду, электричеству и звуку.',jsonb_build_object('version',1,'kind','conditional_movement_and_resistance','dependsOn',jsonb_build_array('state:wrath_of_the_sea_active'),'flySpeed',jsonb_build_object('equals','combat.speed'),'resistances',jsonb_build_array('cold','lightning','thunder'))) where l.template_id=v_id and l.level=10;
    update public.rule_template_levels l set mechanics=private.druid_patch_feature(l.mechanics,'oceanic-gift','При активации Гнева моря его центром можно сделать согласное существо в пределах 60 футов; оно использует Сл заклинаний и Мудрость друида. Потратив 2 использования Дикой формы вместо 1, можно создать эманацию одновременно вокруг друида и вокруг этого союзника. Все дальнейшие улучшения Гнева моря действуют на подаренную эманацию.',jsonb_build_object('version',1,'kind','emanation_origin_override','dependsOnFeature','wrath-of-the-sea','target',jsonb_build_object('willing',true,'rangeFeet',60),'singleOriginCost',1,'dualOriginCost',2,'resource','wild_shape','inherits',jsonb_build_array('aquatic-affinity','stormborn'))) where l.template_id=v_id and l.level=14;
  end if;

  -- STARS
  select id into v_id from public.rule_templates where campaign_id=p_campaign_id and is_active and catalog_key='subclass:druid:stars' order by version desc limit 1;
  if v_id is not null then
    update public.rule_template_levels l set mechanics=private.druid_patch_feature(l.mechanics,'starry-form','Бонусным действием потрать 1 использование Дикой формы и на 10 минут выбери созвездие. Лучник даёт бонусную дальнюю атаку на 60 футов с 1к8 + Мудрость излучающего урона. Чаша после заклинания с ячейкой, которое восстанавливает HP, лечит выбранное существо в 30 футах ещё на 1к8 + Мудрость. Дракон считает результат к20 ниже 10 за 10 на проверках Интеллекта и Мудрости и на спасбросках Телосложения для концентрации.',jsonb_build_object('version',1,'kind','persistent_mode','stateKey','starry_form_active','cost',jsonb_build_object('resource','wild_shape','amount',1),'activation','bonus_action','durationMinutes',10,'modes',jsonb_build_object('archer',jsonb_build_object('action','starry_archer'),'chalice',jsonb_build_object('trigger','slot_spell_restores_hp','extraHealing','1d8+wisdom','rangeFeet',30),'dragon',jsonb_build_object('minimumD20',10,'appliesTo',jsonb_build_array('intelligence_check','wisdom_check','concentration_constitution_save'))))) where l.template_id=v_id and l.level=3;
    update public.rule_template_levels l set mechanics=(select coalesce(jsonb_agg(case when m->>'id'='stars-archer-shot-l10' then jsonb_set(m,'{sourceKey}',to_jsonb('twinkling-constellations'::text),true) else m end order by ord) filter(where m->>'id'<>'stars-starry-form-upgrade-rules'),'[]'::jsonb) from jsonb_array_elements(l.mechanics) with ordinality x(m,ord)) where l.template_id=v_id and l.level=10;
    update public.rule_template_levels l set mechanics=private.druid_patch_feature(l.mechanics,'twinkling-constellations','Пока активна Звёздная форма, в начале каждого своего хода можно сменить созвездие без новой траты Дикой формы. Лучник и Чаша используют 2к8 вместо 1к8; Дракон получает скорость полёта 20 футов и зависание.',jsonb_build_object('version',1,'kind','mode_upgrade','dependsOn',jsonb_build_array('state:starry_form_active'),'switchMode','start_of_turn','archerDamage','2d8+wisdom','chaliceHealing','2d8+wisdom','dragonFly',jsonb_build_object('feet',20,'hover',true))) where l.template_id=v_id and l.level=10;
    update public.rule_template_levels l set mechanics=private.druid_patch_feature(l.mechanics,'full-of-stars','Пока активна Звёздная форма, друид получает сопротивление дробящему, колющему и рубящему урону.',jsonb_build_object('version',1,'kind','conditional_resistance','dependsOn',jsonb_build_array('state:starry_form_active'),'resistances',jsonb_build_array('bludgeoning','piercing','slashing'))) where l.template_id=v_id and l.level=14;
  end if;
end;
$$;

DO $$ declare r record; begin for r in select id from public.campaigns loop perform private.normalize_druid_modern_circles(r.id); end loop; end $$;

commit;
