create table public.app_test (
  id bigint generated by default as identity primary key,
  message text not null,
  created_at timestamptz not null default now()
);

alter table public.app_test enable row level security;

create policy "allow_public_read_app_test"
on public.app_test
for select
to anon, authenticated
using (true);
