-- Character spells are runtime links to the canonical spell catalog.
-- Definitions live in spell_catalog; character tables keep only character-specific state.

create table if not exists public.character_spell_legacy_archive (
  id bigint generated by default as identity primary key,
  source_table text not null,
  source_row_id uuid not null,
  character_id uuid not null,
  payload jsonb not null,
  reason text not null,
  archived_at timestamptz not null default now(),
  unique (source_table, source_row_id)
);

revoke all on table public.character_spell_legacy_archive from anon, authenticated;

alter table public.character_spell_options
  add column if not exists catalog_spell_id uuid;

-- Never guess a catalog identity from copied prose. Preserve historical local
-- definitions for audit, then remove them from the active gameplay model.
insert into public.character_spell_legacy_archive (
  source_table,
  source_row_id,
  character_id,
  payload,
  reason
)
select
  'character_spells',
  s.id,
  s.character_id,
  to_jsonb(s),
  'Missing canonical spell_catalog identity before catalog-only migration'
from public.character_spells s
where s.catalog_spell_id is null
on conflict (source_table, source_row_id) do nothing;

delete from public.character_spells
where catalog_spell_id is null;

insert into public.character_spell_legacy_archive (
  source_table,
  source_row_id,
  character_id,
  payload,
  reason
)
select
  'character_spell_options',
  o.id,
  o.character_id,
  to_jsonb(o),
  'Legacy available spell option had no canonical spell_catalog identity'
from public.character_spell_options o
where o.catalog_spell_id is null
on conflict (source_table, source_row_id) do nothing;

delete from public.character_spell_options
where catalog_spell_id is null;

alter table public.character_spells
  drop constraint if exists character_spells_catalog_spell_id_fkey;

alter table public.character_spells
  alter column catalog_spell_id set not null,
  add constraint character_spells_catalog_spell_id_fkey
    foreign key (catalog_spell_id)
    references public.spell_catalog(id)
    on delete restrict;

alter table public.character_spell_options
  alter column catalog_spell_id set not null,
  add constraint character_spell_options_catalog_spell_id_fkey
    foreign key (catalog_spell_id)
    references public.spell_catalog(id)
    on delete restrict;

drop index if exists public.character_spells_catalog_unique_idx;
create unique index character_spells_catalog_unique_idx
  on public.character_spells(character_id, catalog_spell_id);

create unique index if not exists character_spell_options_catalog_unique_idx
  on public.character_spell_options(character_id, catalog_spell_id);

create or replace function private.sync_character_spell_catalog_projection()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_spell public.spell_catalog%rowtype;
begin
  if new.catalog_spell_id is null then
    raise exception 'Character spells must reference spell_catalog';
  end if;

  select *
    into v_spell
  from public.spell_catalog s
  where s.id = new.catalog_spell_id;

  if v_spell.id is null then
    raise exception 'Catalog spell not found';
  end if;

  -- These columns are compatibility projections for existing renderers. They
  -- are never authored by a character row and are always refreshed from the
  -- canonical catalog before the row reaches storage.
  new.name := coalesce(nullif(v_spell.name_ru, ''), v_spell.name_en);
  new.spell_level := v_spell.spell_level;
  new.school := v_spell.school;
  new.casting_time := v_spell.casting_time;
  new.spell_range := v_spell.spell_range;
  new.duration := v_spell.duration;
  new.components := array_to_string(v_spell.components, ', ');
  new.concentration := v_spell.concentration;
  new.ritual := v_spell.ritual;
  new.description := concat_ws(E'\n\n',
    nullif(v_spell.effect_summary, ''),
    nullif(v_spell.notes, ''),
    nullif(v_spell.upcast, '')
  );
  new.source := v_spell.source;
  new.sort_order := v_spell.sort_order;
  new.cast_mode := case when v_spell.spell_level = 0 then 'cantrip' else 'slot' end;
  new.slot_level := case when v_spell.spell_level = 0 then null else v_spell.spell_level end;

  return new;
end;
$$;

drop trigger if exists character_spells_catalog_projection on public.character_spells;
create trigger character_spells_catalog_projection
before insert or update on public.character_spells
for each row execute function private.sync_character_spell_catalog_projection();

drop trigger if exists character_spell_options_catalog_projection on public.character_spell_options;
create trigger character_spell_options_catalog_projection
before insert or update on public.character_spell_options
for each row execute function private.sync_character_spell_catalog_projection();

-- Rebuild every compatibility projection immediately, so linked rows cannot
-- keep stale copied text from before the invariant existed.
update public.character_spells
set catalog_spell_id = catalog_spell_id;

update public.character_spell_options
set catalog_spell_id = catalog_spell_id;

create or replace function public.learn_character_spell(p_option_id uuid)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_option public.character_spell_options%rowtype;
  v_spell_id uuid;
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  select * into v_option
  from public.character_spell_options
  where id = p_option_id;

  if v_option.id is null then
    raise exception 'Spell option not found';
  end if;

  if not private.can_change_character_spells(v_option.character_id, auth.uid()) then
    raise exception 'Spell changes are locked. GM must grant access after a long rest';
  end if;

  if exists (
    select 1
    from public.character_spells s
    where s.character_id = v_option.character_id
      and s.catalog_spell_id = v_option.catalog_spell_id
  ) then
    raise exception 'Spell is already learned';
  end if;

  -- The trigger resolves every definition field from spell_catalog. The option
  -- contributes only the canonical identity and character-specific prepared flag.
  insert into public.character_spells (
    character_id,
    catalog_spell_id,
    prepared
  ) values (
    v_option.character_id,
    v_option.catalog_spell_id,
    v_option.prepared
  )
  returning id into v_spell_id;

  return v_spell_id;
end;
$$;

comment on column public.character_spells.catalog_spell_id is
  'Required canonical spell_catalog identity. Character rows cannot define spells.';

comment on column public.character_spell_options.catalog_spell_id is
  'Required canonical spell_catalog identity for a learnable option.';
